name: Update ICS files

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: 

jobs:
  update-ics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv chardet 

      - name: Run Python script
        run: |
          python main.py

      - name: Push ICS updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.ics
          git commit -m "Update ICS files" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/lucasstagnette/gpu_edt_lr.git
