name: Run Python script every 30 minutes

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Si tu as un requirements.txt

      - name: Run script
        run: python main.py
